export const News = [
  {
    poster: "Johnte",
    date: "26/6/2025",
    Headline: "Massive Gen-z protests in Kenya",
    post: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur feugiat libero vel dignissim efficitur. In sagittis efficitur dolor in dapibus...............",
    category: "politics",
    upvotes: 0,
  },
  {
    poster: "Maryam",
    date: "27/6/2025",
    Headline: "Tech layoffs spark innovation wave",
    post: "Startup culture in Kenya rises as tech layoffs inspire engineers to build their own platforms..............................................",
    category: "technology",
    upvotes: 3,
  },
  {
    poster: "Kev",
    date: "25/6/2025",
    Headline: "Kenyan artists win international awards",
    post: "Several Kenyan creatives dominate this year's African Art Awards in Johannesburg...........................",
    category: "entertainment",
    upvotes: 12,
  },
  {
    poster: "Johnte",
    date: "24/6/2025",
    Headline: "Massive Gen-z protests in Kenya",
    post: "Second day of protests sees larger turnout as Gen-Z demands economic reforms...............................................................",
    category: "politics",
    upvotes: 8,
  },
  {
    poster: "Achieng",
    date: "23/6/2025",
    Headline: "Kenyan startup launches e-mobility hub",
    post: "The future of green transport: Nairobi startup unveils solar-powered scooter stations....................................",
    category: "business",
    upvotes: 5,
  },
  {
    poster: "Wanja",
    date: "22/6/2025",
    Headline: "Education reforms announced by ministry",
    post: "New curriculum changes aim to reduce exam pressure and emphasize practical learning..................................",
    category: "education",
    upvotes: 2,
  },
  {
    poster: "Tito",
    date: "21/6/2025",
    Headline: "Heavy floods displace thousands in western Kenya",
    post: "The Red Cross steps in as communities face major displacement and infrastructure damage...................................",
    category: "environment",
    upvotes: 6,
  },
  {
    poster: "Linet",
    date: "20/6/2025",
    Headline: "Kenya ranked #1 in mobile money innovation",
    post: "M-Pesa and new fintechs praised in global fintech report for inclusive finance....................................................",
    category: "technology",
    upvotes: 15,
  },
  {
    poster: "Johnte",
    date: "19/6/2025",
    Headline: "Massive Gen-z protests in Kenya",
    post: "Protests spread to Kisumu and Mombasa as youth groups demand accountability...............................................",
    category: "politics",
    upvotes: 11,
  },
  {
    poster: "Ray",
    date: "18/6/2025",
    Headline: "Rising mental health concerns in Kenyan universities",
    post: "Students call for increased support and better counseling services....................................",
    category: "health",
    upvotes: 7,
  },
];
